### ISSUE TITLE
oUF_Diablo hides wow interface

### ISSUE THREAD

**Issue by makito89** [zorker/rothui#11]
Hello.

I know that this addon is old but I want to patch it so it can be used in Legion. I've manage to patch the unit plates (can give you the patches for oUF and oUF_Diablo to merge them into the code) but there is another issue that I do not know from where to start to fix it.

The issue is when the Power bar is dropping under 10% all the UI elements except the text disappear (Can be seen in the following screen shot [http://charlatans.wow-guilds.eu/pics/bug_1.png](url) - from the wow system menu only the text are visible - from heal bot also only the texts - from the bags only the amount of items are visible). This behavior is triggered when power drops under 10% or when I use a portal with a character that has 0 power. Everything gets back to normal when the power is above 10%.  So I will apreciate if you can help me with this or point me from where to start how to investigate the issue.

There is also a small visual bug that affects the orbs animations - the animations drop at the same time with the background color of the health and power orb - before legion it did not happen - but when they restore the animation remains to the lowest level (this can be seen in the following picture [http://charlatans.wow-guilds.eu/pics/bug_2.png](url) )

Best regards and thank you for your work

**Comment by zorker** [comment]
oUF_Diablo that is compatible with WoW 7.0 (Legion). Make sure to only use WoW 7.0 (Legion) compatible addons.

**Comment by makito89** [comment]
Thank you for the quick reply. I do not have other addons than Recount, Healbot and oUF_Diablo with rChat and rInfoStrings. All of those are updated to latest versions. But I did a quick test. Disabled them all except oUF and oUF_Diablo and I get the same behavior. Without oUF_Diablo everything is ok.

**Comment by zorker** [comment]
What the heck. I forgot a pretty important _NOT_. Sorry it should have read: oUF_Diablo is **not** compatible with WoW 7.0 (Legion).

**Comment by makito89** [comment]
Now I got it. I'd greatly appreciate if you can give me a hint from where should I start as I do like to make it compatible with 7.0

**Comment by zorker** [comment]
Galaxy is working on it. https://github.com/galaxy119/oUF_Diablo/

**Comment by makito89** [comment]
Thank you for info.
