### ISSUE TITLE
checked, pushed and highlight texture

### ISSUE THREAD

**Issue by mtthsw** [zorker/rothui#12]
Hey,

I don't know if you are aware of this but when I try to use the these three found in the [documentation](https://github.com/zorker/rothui/tree/master/wow7.0/rButtonTemplate)  in my layout  ...

``` lua
   actionButtonConfig.pushedTexture
   actionButtonConfig.highlightTexture
   actionButtonConfig.checkedTexture
```

... I get the following error:

> Message: Interface\AddOns\rButtonTemplate\core.lua:104: attempt to call global 'CallObjectFunction' (a nil value)
> Time: 07/28/16 22:16:56
> Count: 1
> Stack: Interface\AddOns\rButtonTemplate\core.lua:104: in function <Interface\AddOns\rButtonTemplate\core.lua:93>
> Interface\AddOns\rButtonTemplate\core.lua:169: in function `StyleActionButton'
> Interface\AddOns\rButtonTemplate\core.lua:262: in function`StyleAllActionButtons'
> Interface\AddOns\rButtonTemplate_Lyn\theme.lua:163: in main chunk

my theme looks like this (pushedTexture example):

``` lua
actionButtonConfig.pushedTexture = {
    file = mediapath.."border",
    color = {1, 1, 0, 1},
    points = {
        {"TOPLEFT", -1, 1 },
        {"BOTTOMRIGHT", 1, -1 },
    },
}
```

I dunno exactly WHY this happens, maybe he can't find the right function? Seems like this.
But I already fixed it in my version the following way by adding three functions and adding them to `SetupTexture()`:

``` lua
local function ApplyPushedTexture(button,file)
  if not file then return end
  button.__pushedTextureFile = file
  button:SetPushedTexture(file)
  hooksecurefunc(button, "SetPushedTexture", ResetPushedTexture)
end

local function ApplyHighlightTexture(button,file)
  if not file then return end
  button.__pushedTextureFile = file
  button:SetHighlightTexture(file)
  hooksecurefunc(button, "SetHighlightTexture", ResetHighlightTexture)
end

local function ApplyCheckedTexture(button,file)
  if not file then return end
  button.__checkedTextureFile = file
  button:SetCheckedTexture(file)
  hooksecurefunc(button, "SetCheckedTexture", ResetCheckedTexture)
end

local function SetupTexture(texture,cfg,fileFunc,fileObj)
  if not texture or not cfg then return end
  ApplyTexCoord(texture,cfg.texCoord)
  ApplyPoints(texture,cfg.points)
  ApplyVertexColor(texture,cfg.color)
  ApplyAlpha(texture,cfg.alpha)
  if fileFunc == "SetTexture" then
    ApplyTexture(texture,cfg.file)
  elseif fileFunc == "SetNormalTexture" then
    ApplyNormalTexture(fileObj,cfg.file)
  elseif fileFunc == "SetPushedTexture" then
    ApplyPushedTexture(fileObj,cfg.file)
  elseif fileFunc == "SetHighlightTexture" then
    ApplyHighlightTexture(fileObj,cfg.file) 
  elseif fileFunc == "SetCheckedTexture" then
    ApplyCheckedTexture(fileObj,cfg.file)    
  elseif cfg.file then
    CallObjectFunction(fileObj,fileFunc,cfg.file)
  end
end
```

**Comment by zorker** [comment]
Args I renamed that function. :)
Gonna fix it asap.
_edit_ Fix is applied.
