### ISSUE TITLE
phantom buff button

### ISSUE THREAD

**Issue by mtthsw** [zorker/rothui#14]
I am not exactly sure if it's a problem with the buff frame - or the skinning addon - but I am getting a phantom buff icon above my normal buffs.

You can reproduce it like this:
- Having a buff
- Using a vehicle which does you give posession
- reload ui 
  -> phantom button
  ![wowscrnshot_072916_223627](https://cloud.githubusercontent.com/assets/868385/17262657/ec7e16f0-55dc-11e6-8090-54406bad46b9.jpg)

**Comment by zorker** [comment]
What does /fstack tell you about that button?

**Comment by mtthsw** [comment]
Oh, sorry, haven't got the notification, will tell you tonight!

**Comment by mtthsw** [comment]
Finally! Sorry it took so long. I tested it in Ulduar, one of the vehicles.
![unbenannt-1](https://cloud.githubusercontent.com/assets/868385/17412504/565704f2-5a7d-11e6-9406-b4a534e29035.png)
Oh, now I see it ... TempEnchant3 must be from Buff addon, but .. oUF_PetBattleFrameHider?

**Comment by joker-119** [comment]
Correct me if I'm wrong but oUF_PetBattleFrameHider
Sounds like the frame space used by oUF to hide your buffs/debuffs when you enter a pet battle.

**Comment by mtthsw** [comment]
Maybe, dunno, but I wasn't in a pet battle. Anyway, also there is `TempEnchant3`. That's what I am referring to.

**Comment by zorker** [comment]
The oUF petbattle frame is just a frame used by haste where all oUF frames are anchored that hides itself in [petbattle]. I will look into the TempEnchant3 problem.

**Comment by zorker** [comment]
Tested it. Cannot reproduce the bug. http://imgur.com/a/MXyni
Biggest engine in Ulduar has a Lua error btw (Blizzard Lua error).

**Comment by mtthsw** [comment]
Oh well. I will test around. Thought it has to be the Buff Frame (because
of the skin and position). If it's not, sorry for bothering. :)
