### ISSUE TITLE
rActionBar issues with moving Stance and MicroMenuBar

### ISSUE THREAD

**Issue by joker-119** [zorker/rothui#15]
Using the newest version of rActionBar moving the micromenubar and the stance bar seems to function normally until the UI is reloaded, a loading screen is encountered or you relog. Upon any of these events the position of these 2 bars resets to their default.

**Comment by zorker** [comment]
Will look into it. Sounds wonky since the bar anchors to the hardcoded positions perfectly.

**Comment by zorker** [comment]
Ok found the problem. I delay the bar creation on those two bars for differen reasons. But that does not work for UserPlaced frames. Those need to be set on init, not PLAYER_LOGIN. Will think about a workaround.

**Comment by orangepaw3** [comment]
Awesome was just coming to report this (late as usual) thank you Zorker!

**Comment by zorker** [comment]
Issue is fixed.
