### ISSUE TITLE
rActionBar will not allow users to change active actionbar in some druid forms and stealth

### ISSUE THREAD

**Issue by joker-119** [zorker/rothui#18]
rActionBar prevents users from scrolling to different actionbars when in Bear of Cat forms or while Stealthed.

I'm assuming this has something to do with how the addon handles setting ActionBar1 to the correct bar for said forms and stealth?  I don't have the time to see if this can be worked around or not.

**Comment by zorker** [comment]
It does. You need to set a specific visibilityHandler in your actionbar config. If none is provided the default one is used. https://github.com/zorker/rothui/blob/master/wow7.0/rActionBar/bars.lua#L83
