### ISSUE TITLE
rActionBar vehicle UI

### ISSUE THREAD

**Issue by joker-119** [zorker/rothui#19]
There is no override bar for the vehicle UI in rActionBar
Not entierly sure how to go about adding one.

**Comment by zorker** [comment]
There is no overridebar any more. I changed how actionbar pages are handled back to the onstate-page handler. https://github.com/zorker/rothui/blob/master/wow7.0/rActionBar/bars.lua#L83

**Comment by zorker** [comment]
My bad. I forgot to add the onstate-page config variable to the config. Will add it as a new optional variable next to frameVisibility.
