### ISSUE TITLE
action bar issue

### ISSUE THREAD

**Issue by fafaraway** [zorker/rothui#25]
hey zork, have you done this quest http://www.wowhead.com/quest=44479/ravencrests-legacy
in this scenario, player will get usable spell one by one, but rActionbar cant show those spell button correctly, so I have to disable rActionbar and use default action bar to finished the scenario, maybe a bug I guess, hope you can check it while you doing that quest.

**Comment by zorker** [comment]
That is a known issue. The buttons will appear correctly after mouse over. Not sure what screws them up. The page id is correct. Fix for now is to hover the button for a brief second.
