### ISSUE TITLE
oUF Simple suggestions

### ISSUE THREAD

**Issue by solumg** [zorker/rothui#26]
Just some ideas for futher development, if you'r interested :P
- Animated(smooth) bars.
- Power prediction.
- Show power numbers.
- Option to color border threat instead of healthbar.
- Fade out castbar(like to show failed or successfull).

**Comment by zorker** [comment]
Thanks for the suggestions.

That is something I will not do in full. The layout itself will become modular with a set of functions and configuration options. But it will not turn into a jack of all trades. Of course you can use oUF_Simple as a base to create your own version that supports your personal taste.

We will see how far it evolves in the next days/weeks. Still early development.
