### ISSUE TITLE
Runes for DK

### ISSUE THREAD

**Issue by daneras** [zorker/rothui#28]
Hello Zork,

i use your UF now and can't find the Runes for the DK. Are they hidden or something else?
Thanks for a quick feedback.

Greetings,
Daneras

**Comment by zorker** [comment]
No. I assumed DKs would use their prefered rune addon anyway like this one: http://www.wowinterface.com/downloads/info21363-VexRunes.html
Sadly DK runes did not get changed to a classbar. That would have been convenient. I will leave this open for now. Not sure if I want to add them.

**Comment by daneras** [comment]
Morning, ok, thx for the answer. I will use a Addon in this case. Was just wondering.
