### ISSUE TITLE
exp/rep/artifact.. bar

### ISSUE THREAD

**Issue by solumg** [zorker/rothui#30]
Do you have any plans to implement said feature? And btw is it intended that the out of range, out of mana etc. color, is limited to the hotkey and not the whole button?

**Comment by zorker** [comment]
For oor coloring use tullaRange.
Exp is easily done with a macro.
Artifact and rep are just one keybind away. No need for a seperate bar. You can install an addon for those if you like.

**Comment by solumg** [comment]
Yes tullaRange ofc. Macro as in chat output? And what do you mean by "one keybind away"? Please elaborate.
Thanks.

**Comment by zorker** [comment]
Artifact bar is shift right-click on the artifact weapon. You have all information when you hover the icon in your artifact window.
Reputation has its own interface panel. Check your keybindings.
Yes a macro for xp.

```
/run local x,m=UnitXP("player"),UnitXPMax("player"); print(math.floor((x/m)*100))
```
