### ISSUE TITLE
Suggestion: Cooldown framelevel

### ISSUE THREAD

**Issue by mtthsw** [zorker/rothui#31]
**Suggestion for rButtonTemplate**

Since I make my UI more or less in the look of Blizzard, I found something which disturbs me a bit. Maybe it is something you could also add in the base addon. I am talking about changing the framelevel of the cooldown spiral.

```
local function SetupCooldown(cooldown,cfg)
    if not cfg then return end
    ApplyPoints(cooldown, cfg.points)
    if cfg.frameLevel then
        cooldown:SetFrameLevel(cfg.frameLevel)
    end
end
```

And then someone can add `frameLevel` as a value in his config for the cooldown.

**Comment by zorker** [comment]
Why exactly?

**Comment by zorker** [comment]
If you have problems with the cooldown placement adjust the point.

**Comment by mtthsw** [comment]
Because the cooldown spiral overlaps the hover texture if you make it inside, like Blizzard's buttons.

**Comment by mtthsw** [comment]
It has nothing to do with the position. As I said.

**Comment by zorker** [comment]
Thanks. Will look into it.
