### ISSUE TITLE
Sometime it fails to detect exit from combat

### ISSUE THREAD

**Issue by ggiovannelli** [zorker/rothui#32]
Hi Zork,

sometime OUF_Simple fails to check the exit from combat condition.

https://s14.postimg.org/n8qwha5s1/screenshot_352.png

As you see in the screenshot I am able to summon the mount even if the player frame shows me in combat.

If I (as druid) shapeshifts ... this fixes the problem or you can wait a little bit more and then it fixes it too.

Thanks.

**Comment by zorker** [comment]
I noticed that aswell. That is no combat indicator but a threat indicator. Threat events do not fire properly if you oneshot mobs or if you have not taken any damage in the fight. I thought about adding the combat events to the threat event list and will probably do so. Thanks.

**Comment by ggiovannelli** [comment]
Thanks :)

**Comment by zorker** [comment]
Keep this open until I could test it.
Actually not that easy since there is no unit event for combat. Only one for player which is not enough.
Ignoring it for now. It is a non-issue in most cases.

**Comment by ggiovannelli** [comment]
Hi Zork, 

I'd like to ask if you could think to add a condition configuration based on events PLAYER_REGEN_DISABLED / PLAYER_REGEN_ENABLED to trigger a unitframe change accordingly ? 

Because sometimes you are in combat but you don't have aggro (i.e. when you have a bodyguard from the garrison / class hall I think ... ) 

Thanks again from your great stuffs :)

**Comment by zorker** [comment]
That will work for player only. There is no unit event that fires when a unit enters combat. There is a function to check if any unit is affected by combat but that does not help if there is no trigger.

**Comment by ggiovannelli** [comment]
I understand that in this way it will work for player only, but what I 'd like to have is an indicator on player unit frame that tell me when I am in combat or no :) You should probably use the 2 swords crossed in the place of zzz icon ? 

For this I don't care about the target I only need to know, for example, if I can cast the mount or not :) 
Now sometimes I have my unit frame class colored (because I have no aggro) but I am in combat ... or viceversa as we discuss in the first posts :)

Really thanks for your kind attention.
