### ISSUE TITLE
Show keybind

### ISSUE THREAD

**Issue by pntbutter** [zorker/rothui#34]
With my limited knowledge of wow addon code, I could not find anything regarding keybind text with rActionBar.

Can I enable this somewhere? If not, is it something you plan to implement?

Thanks for being an awesome addon author!

**Comment by zorker** [comment]
Open the button theme for the button template you are using. Probably rButtonTemplate_Default or rButtomTemplate_Zork. Open the theme.lua and set the alpha of the hotkey settings from 0 to 1.
https://github.com/zorker/rothui/blob/master/wow7.0/rButtonTemplate_Zork/theme.lua#L155
