### ISSUE TITLE
CastBars & times

### ISSUE THREAD

**Issue by ggiovannelli** [zorker/rothui#36]
I Zork, 

is possible to add or to configure in the castbars (player and target) the casting time ?

Thanks very much.

![wowscrnshot_110616_091607](https://cloud.githubusercontent.com/assets/17082136/20036240/eb9daeb6-a402-11e6-8257-287933f3435f.jpg)

**Comment by zorker** [comment]
Hmmm. I could add the oUF time fontstring. Not sure if I want to though. Castbar timer is not needed imo.

**Comment by ggiovannelli** [comment]
I agree with you that it is not a so mandatory thing to have, but a couple of friends asked if it will possible to have because they have habits to see it :) and I reported to you :)

Btw if it is a a problem we can happily ignore them :)

**Comment by zorker** [comment]
Ignored for now.
