### ISSUE TITLE
rchat: scroll button 

### ISSUE THREAD

**Issue by ggiovannelli** [zorker/rothui#37]
Hi Zork,

I don't want to stress you so much ... just a suggestion this time :)
In rchat if you scroll up and then you don't come back to the last line of chat you loose any feedbacks on the chat ... so person write but you don't understand this because your chat remain stopped.

It should be possible to have a button that appears when you scroll up so:
1) you understand that your chat is not realtime but it is scrolled.
2) you can press it to go to the last (current)  line without have to use 2 hands...

Thanks ... and sorry to the disturb ... :)

**Comment by zorker** [comment]
No thanks. Shift + scrolldown. Scrolls to the bottom instantly.
You can of course hack that in yourself.
