### ISSUE TITLE
OUF_Simple and layout dependency

### ISSUE THREAD

**Issue by ggiovannelli** [zorker/rothui#38]
Hi Zork, 
should be possible to use also for OUF_Simple a dependency system like are rActionBar and  rButtonTemplate for example ? 

Now it depends statically by a template which name is only "oUF_SimpleConfig", but this prevents others to make more templates addons for the engine being the name statically written in OUF_Simple.toc

It should, IMHO, the layout that had to depend by the engine not the viceversa :) Or if you want you can throw an error message if the layout is not found like "Missing template layout, please download ones ... " :) 

Thanks again for everything :)

**Comment by zorker** [comment]
I thought about that while writing it. I decided against it since oUF_Simple is not a framework but a template with a big config. I just needed a way to seperate the config from the core addon so people can update the core addon without interfering with their config.
