### ISSUE TITLE
rActionbar cannot modify micromenubar

### ISSUE THREAD

**Issue by Inphon** [zorker/rothui#40]
local micromenubar = {
  framePoint      = { "BOTTOMLEFT", UIParent, "BOTTOMLEFT", 0, 0 },
  frameScale      = 0.8,
  framePadding    = 5,
  buttonWidth     = 28,
  buttonHeight    = 58,
  buttonMargin    = 0,
  numCols         = 12,
  startPoint      = "BOTTOMLEFT",
  fader           = nil,
}

I want micromenubar show in bottomleft but not work.

**Comment by zorker** [comment]
The position data is saved into savedvariables and loaded from their. If you want to activate a new default position type this ingame in chat after you made changes to the lua file:

```
/reload
/rabs reset
```
