### ISSUE TITLE
Cannot modify OUF_Simple Player layout position

### ISSUE THREAD

**Issue by Inphon** [zorker/rothui#41]
L.C.player = {
  enabled = true,
  size = {265,26},
  point = {"RIGHT",UIParent,"CENTER",-120,-120},
  scale = 1*L.C.globalscale,

player.lua

once one character was login game, this position cannot change anymore.
but no more config file in WTF folder. how to revise it?

**Comment by zorker** [comment]
The position data is saved into savedvariables and loaded from their. If you want to activate a new default position type this ingame in chat after you made changes to the lua file:

```
/reload
/rsim reset
```
