### ISSUE TITLE
oUF

### ISSUE THREAD

**Issue by illum1n4ti** [zorker/rothui#46]
Hello Zorker

I am trying to fix here and there some bugs and i have to say it goes well but i am wondering if you could update your addon with the new oUF or rather would be nice if the your addons doesn't use custom oUF. 

I hope to hear from u soon

**Comment by zorker** [comment]
Currently not playing WoW, so no. Otherwise I would do it asap. The nameplate feature is now part of the oUF core and I could get rid of the embedded oUF.

**Comment by illum1n4ti** [comment]
Hello zorker

It would be nice if you could did get rid of embedded oUF

Thanks again and hope to see u playing wow again :)

**Comment by zorker** [comment]
I already did that.

**Comment by illum1n4ti** [comment]
Zorker

I am sorry i did not see it .. Thank you buddy for doing this. One more thing i know the nameplate is part of oUF .. I was missing the Mirrorbar. i wrote something like this. what u think?

-----------------------------
-- Mirror Castbar
-----------------------------
MirrorTimerColors = { };
MirrorTimerColors["EXHAUSTION"] = {	r = 1.00, g = 0.90, b = 0.00 };
MirrorTimerColors["BREATH"] = {	r = 0.00, g = 0.50, b = 1.00 };
MirrorTimerColors["DEATH"] = { r = 1.00, g = 0.70, b = 0.00	};
MirrorTimerColors["FEIGNDEATH"] = {	r = 1.00, g = 0.70, b = 0.00 };

for i = 1, MIRRORTIMER_NUMTIMERS do
    local bar = _G['MirrorTimer'..i]
    bar:SetParent(UIParent)
    bar:SetScale(0.9)
    bar:SetWidth(300)
    bar:SetHeight(20)

    if (i > 1) then
        local p1, p2, p3, p4, p5 = bar:GetPoint()
        bar:SetPoint(p1, p2, p3, p4, p5 - 15)
    end

    local statusbar = _G['MirrorTimer'..i..'StatusBar']
    statusbar:SetStatusBarTexture("Interface\\AddOns\\FXPmedia\\bar\\texture")
    statusbar:SetAllPoints(bar)

    local backdrop = select(1, bar:GetRegions())
    backdrop:SetTexture("Interface\\AddOns\\FXPmedia\\bar\\texture")
    backdrop:SetVertexColor(0.28, 0.28, 0.28, 1)
    backdrop:SetAllPoints(bar)

    local border = _G['MirrorTimer'..i..'Border']
    border:Hide()
    -- Border need to be fixed
    -- border:SetTexture("Interface\\AddOns\\FXPmedia\\border\\castborder")
    -- border:SetVertexColor(.25, .25, .25)
    -- border:SetWidth(400)
    -- border:SetHeight(126)
    -- border:SetPoint("CENTER", 0, 5)

    local text = _G['MirrorTimer'..i..'Text']
    text:SetFont("GameFontHighlight", 10)
    text:ClearAllPoints()
    text:SetPoint('CENTER', bar)
end

**Comment by zorker** [comment]
Mirror timers are not unit specific and can be handled in a small addon on its own.

https://github.com/tomrus88/BlizzardInterfaceCode/blob/master/Interface/FrameXML/MirrorTimer.xml
https://github.com/tomrus88/BlizzardInterfaceCode/blob/master/Interface/FrameXML/MirrorTimer.lua

To position the timers you can create a small square frame on UIParent and reparent and repoint MirrorTimer1 to the center of that frame. That way you can add a drag function and move around the timers at will. I will look into it once the PTR client has finished downloading.
