### ISSUE TITLE
(Balance Druid) Proc Highlighting

### ISSUE THREAD

**Issue by eculley** [zorker/rothui#47]
Hey there, 

Installed the new version this morning and am noticing Starsurge is definitely highlighting solar wrath, but not lunar strike empowerment. 

https://imgur.com/a/MYg1d

The top left and the icon next to it are both empowered and should be highlighted.

**Comment by zorker** [comment]
That sounds wierd because I do not interfere with those textures. Does it show when disabling rActionBar and rButtonTemplate aka default Blizzard actionbar?

**Comment by zorker** [comment]
Just tested it. It is working properly. https://imgur.com/a/HLXfB
