### ISSUE TITLE
Add a buff time remaining overlay to rButtonaura.

### ISSUE THREAD

**Issue by arcadepro** [zorker/rothui#48]
This would would allow you to see the time remaining on Ignore Pain/Shield Block etc.

**Comment by zorker** [comment]
A timer with a text would be meh. 

I thought about it. There are two practical solutions. We could change the button border height based on aura time remaining. Alternatively we could add a new texture as a new statusbar that stands for the aura uptime. The latter is how Diablo 3 and PoE (flasks) do it. That could even replace the button border coloring.

**Comment by arcadepro** [comment]
I feel numbers are better since the whole game revolves around lining things up correctly. Guessing how long is left based on the height/state of a moving texture is kind of annoying. For long cooldowns it works 'OK' but for abilities like block/IP and so on I'd really want to know how long is left.

**Comment by zorker** [comment]
The biggest issue is the space. 
http://cdn-wow.mmoui.com/preview/pvw69469.png

There are already so many strings in place. Shield block for example has cooldown and stack for two, if you count the keybind that is three. If your button is tiny like the ones below there is even less space.

rFilter or WeakAuras can provide you with specific buttons with cooldowns tied to the aura durations.
On actionbuttons I see no viable way of doing it.

**Comment by arcadepro** [comment]
Yeah it's a small space. However, if it's OK to have spell charges in the bottom right, what's wrong with having the time remaining in the bottom left?

https://screenshots.firefox.com/N7Ghyi8W344xP7Wp/null
