### ISSUE TITLE
Double power bar ?

### ISSUE THREAD

**Issue by jeanbaptiste-brasselet** [zorker/rothui#49]
Hello, 

I tried to play a little bit with the code but I am currently playing a shadow Priest and I didn't manage to display both the Insanity/mana bar ? Could you help me ?

**Comment by zorker** [comment]
Currently I do not display the additional power bar in oUF_Simple.
There is no room for another bar. But you can use oUF tags to display the mana value as a text.
I will try to post an example later.

Links:
https://github.com/oUF-wow/oUF/blob/master/elements/additionalpower.lua
https://github.com/tomrus88/BlizzardInterfaceCode/blob/master/Interface/FrameXML/AlternatePowerBar.lua

**Comment by jeanbaptiste-brasselet** [comment]
Ok :) I will have to dig more then. What is https://github.com/zorker/rothui/blob/master/wow7.0/oUF_SimpleConfig/player.lua#L98-L102 (altpowerbar) / https://github.com/zorker/rothui/blob/master/wow7.0/oUF_Simple/core/style.lua#L29 ?

**Comment by zorker** [comment]
The alternative powerbar is used in vehicles and raids. It is a special encounter specific bar. It is used in certain vehicles too.

**Comment by zorker** [comment]
On that topic. If you have Insanity. Why does your mana bar matter?

**Comment by jeanbaptiste-brasselet** [comment]
Well you have two phase and in one of them you are using the mana ! As a matter of fact I ran out of it the other day without realizing it !
And I am curious to know how lua works and all so I decided to look but it is not as simple as it seems !
