### ISSUE TITLE
rButtontemplate + Dominos

### ISSUE THREAD

**Issue by arcadepro** [zorker/rothui#52]
![wowscrnshot_021918_184358](https://user-images.githubusercontent.com/1977760/36396066-1f68d3c8-15b4-11e8-87db-aae272717468.jpg)

Commenting out line 185 in rbuttontemplate/core.lua will fix it but is there a better way?

Apart from these ghost button borders everything works fine. (Aside from the extra action button, it shares the same bug)

**Comment by zorker** [comment]
Not sure if that is possible. You probably still use StyleAllActionButtons. That is for Blizzard buttons only. https://github.com/zorker/rothui/blob/master/wow7.0/rButtonTemplate/core.lua#L305
Use StyleActionButton instead. You may need to add Dominos as a required dependency to your toc file. It may also be required to register a callback or event if the buttons are not available on addon init and style the button once they are available.
