### ISSUE TITLE
Update to Legion

### ISSUE THREAD

**Issue by uonick** [zorker/rothui#53]
Hi Erik!
Thanks for the beautiful addons!

Yesterday I updated the addon to the Legion version, but I can not understand how to return the highlight of the class in the target. Please help!

### Before: 
<img width="371" alt="screen shot 2018-04-17 at 23 42 31" src="https://user-images.githubusercontent.com/365029/38889766-13eb8ff6-4299-11e8-8192-9d66abf24620.png">
<img width="443" alt="screen shot 2018-04-17 at 23 42 43" src="https://user-images.githubusercontent.com/365029/38889767-140aafd0-4299-11e8-9989-ce957aac2516.png">

### After:
<img width="642" alt="screen shot 2018-04-17 at 23 41 49" src="https://user-images.githubusercontent.com/365029/38889774-18534796-4299-11e8-8082-9397cddba004.png">

Look here: https://github.com/uonick/rothui/tree/master/wow7.3

And i want to add PR for the update version =)

P.S: yes i know about [this version](https://github.com/galaxy119/Roth_UI), but this version is.... 👎

**Comment by zorker** [comment]
Either this is not returning anything useful https://github.com/uonick/rothui/blob/master/wow7.3/oUF_Diablo/core/lib.lua#L271 or the color is reset somewhere else.
