### ISSUE TITLE
Feature request for rCompassCastbar.

### ISSUE THREAD

**Issue by Cluuey** [zorker/rothui#55]
Thanks for the update to make it work in Legion.

There are a few requests to be able to show the GCD, can you make that happen?
A resto druid casts many, many instant HoT's. This means you're looking at your cursor to position it over a raid frame, it would be very beneficial to have the GCD displayed where you're already looking.

**Comment by zorker** [comment]
The GCD would be just the action button cooldown of a class specific spammable spell that has no castbar and long cooldown on its own, right?

**Comment by Cluuey** [comment]
Yes.
Resto druid casts a lot, a crazy amount, of Rejuvination:
http://bfa.wowhead.com/spell=774/rejuvenation

It is effected by haste though, I think most healer spells are.
