### ISSUE TITLE
about unitframe frame visibility

### ISSUE THREAD

**Issue by fafaraway** [zorker/rothui#57]
hey zork, is that possible to use frame visibility feature to show player frame when player's health low than a certain percentage

`"[combat][mod][@target,exists,nodead][@vehicle,exists][overridebar][shapeshift][vehicleui][possessbar] show; hide"`

**Comment by Goldpaw** [comment]
Macro drivers cannot check for amount of health, power, active auras or any such specifics. So secure frames like clickable unitframes or clickable actionbuttons can't be fully toggled at certein health percentages, it's just not possible. 

Alpha/opacity can be changed, but through normal lua and normal scripts, not through macro drivers.

**Comment by fafaraway** [comment]
thanks for explain @goldpaw 👍
