### ISSUE TITLE
Possible rStatusButton issue

### ISSUE THREAD

**Issue by AngelosNaoumis** [zorker/rothui#58]
Trying to modify my StatusButton to be always visible,
I edited framevisibility to:
`frameVisibility = "show",`
but now if I hover over the position of it I can only see the tooltip, there is no texture (neither active nor inactive)

Clicking it does not change the texture either.

**Comment by zorker** [comment]
If you set the frameVisibility to "show" you need to remove the fader from the config. It has an OnShow trigger for alpha handling that will not fire anymore since the frame is always shown. The frame is shown just transparent.
```lua
local cfg = {
  scale = 0.9,
  point = { "TOP", 0, -150 },
  size = { 32, 32 },
  frameVisibility = "show",
  frameVisibilityFunc = nil,
}
```
