### ISSUE TITLE
Not an issue but a question about how to manage the git repo

### ISSUE THREAD

**Issue by AdenJustice** [zorker/rothui#60]
First of all, apologies using this issue tracker as something like a forum. But I'm really curious
 about how you manage the add-on git repos. I mean, for example, under "Wow 8.0" there are several add-ons you probably use in-game and develop at the same time. With my humble knowledge, I can't figure out how to sync(?) the git repo and Wow AddOn folder. If it's not a big deal, please tell me the tips.

**Comment by fafaraway** [comment]
if you are using windows system, `mklink` is a good solution 🤣

**Comment by zorker** [comment]
My git folder is somewhere else. I just use it as a pastebin of projects I have laying around in my wow folder.
