### ISSUE TITLE
rActionBar Usage / Permissions

### ISSUE THREAD

**Issue by kaytotes** [zorker/rothui#61]
I've been looking at rActionBar for a few days and was hoping to use it within my addon Improved Blizzard UI which I've been tinkering with since late MoP. Up until very recently I've been trying to avoid the usage of libraries but have started porting it over to be mainly Ace3 and oUF for unit frames. I'm looking for a decent action bar library and yours looked like it fit the bill.

Do you have any opposition to me pulling in rActionBar as a library then using that to generate my action bars? I ask this because while many UI packages are a bundling of addons (where your name would be prominent on the addon list etc) mine is largely all my own lua up to this point. Considering rActionBar would be acting as a library I would of course be insisting on very plainly putting in the readme of the project the relevant credit towards yourself.

**Comment by zorker** [comment]
Sure you can do that.
