### ISSUE TITLE
Addon breaks on new 8.1.5 patch

### ISSUE THREAD

**Issue by Dajova** [zorker/rothui#62]
I'm guessing you dont read WoWI all that often anymore, so i'll just post it here:

``
for i, button in next, itemButtons do
  rButtonTemplate:StyleItemButton(button, itemButtonConfig)
end
``

That line is breaking the addon since 8.1.5, casuing this error:

``
4x rButtonTemplate\core.lua:283: attempt to call method 'GetCheckedTexture' (a nil value)
rButtonTemplate\core.lua:283: in function `StyleItemButton'
rButtonTemplate_Shadow\theme.lua:171: in main chunk
``

**Comment by zorker** [comment]
Issue is fixed by https://github.com/zorker/rothui/commit/642c4dca86afbd5f7e7e7bf42ef40e9efad02297
