### ISSUE TITLE
Blizz 6.2.2 API change breaks rNameplates

### ISSUE THREAD

**Issue by arcadepro** [zorker/rothui#7]
Just posting this here just in case you've abandoned wowinterface.com :)

> You can get things working by changing (@ln 195 or so in rnameplates.lua)
> blizzPlate.healthBar, blizzPlate.castBar = blizzPlate.barFrame:GetChildren() to
> blizzPlate.healthBar, _, blizzPlate.castBar = blizzPlate.barFrame:GetChildren()
> 
> Bars are also now only using 0 to 1 for values. You cant query exact values any more.
> Some of the changes made to kui nameplates for 6.2.2 can be seen here
> https://github.com/kesava-wow/kuinameplates/commit/359e32c86b6e473fa42546f2600af733dec5a882

http://www.wowinterface.com/downloads/info22478-rNamePlatesDiablo.html#comments

**Comment by zorker** [comment]
Fixed.
