### ISSUE TITLE
Bugging with talents tab.

### ISSUE THREAD

**Issue by ghost** [zorker/rothui#9]
After reload and choose talents tab, i get next 
![wowscrnshot_072316_164824](https://cloud.githubusercontent.com/assets/13165450/17077754/8c7ad1c6-50f5-11e6-93ce-703740fa458c.jpg)

**Comment by zorker** [comment]
Currently I have no full UI that supports WoW 7.0. Make sure to only use WoW 7.0 (Legion) compatible addons.
